
name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "node"

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm build
      env: 
        PUBLIC_BREVO_CONVERSATIONS_ID: ${{ vars.PUBLIC_BREVO_CONVERSATIONS_ID }}